# Use postgres/example user/password credentials
version: '3.9'

name: postgres
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgreSQL_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    volumes:
      - postgres:/data/postgres
volumes:
    postgres:
