import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Header";
import {
  ClerkProvider,
} from '@clerk/nextjs'
export const metadata: Metadata = {
  title: "Movibes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning >
      <body suppressHydrationWarning>
        <ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
        >
          <main className="px-8 max-md:px-4">
            <div className="max-w-screen-2xl mx-auto">
          <Header/>
        {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
